# Pytorch

### Tensor Operations

A short introduction about PyTorch and about the chosen functions. 
- function 1: backward
- function 2: torch.where(condition, x, y) 
- function 3: torch.unique()
- function 4: tensor.repeat()
- function 5: tensor.fill_diagonal_(fill_value)

In [2]:
# Import torch and other required modules
import torch

## Function 1 - backward

In case, the learning algorithm we are using is Gradient Descent. We need to calculate the derivative of loss against the parameters given. The backward function automates this task. The model parameters need to have requires_grad set to True. In order to calculate derivative, call backward() function on the tensor. The derivatives of tensor w.r.t the input tensors are stored in the .grad property of the respective tensors.

In [3]:
# Example 1 - working 
x = torch.tensor(3.)
w = torch.tensor(5., requires_grad=True)
b = torch.tensor(9., requires_grad=True) 
y = w*x + b
y.backward()
print("dy/dx:", x.grad) 
print("dy/dw:", w.grad) 
print("dy/db:", b.grad) 

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


Here y is a function of input x and parameters w and b. Since we have not set requires_grad=True for x, by default it is false and hence its grad is None. Derivation of y w.r.t w results in x, and its derivation w.r.t b results is 1, as expected.

In [4]:
# Example 2 - working
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True)
b = torch.tensor(5., requires_grad=True)
y = w * x + b
y.backward()
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


As expected, dy/dw has the same value as x i.e. 3, and dy/db has the value 1. Note that x.grad is None, because x doesn't have requires_grad set to True.

In [65]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=False)
b = torch.tensor(5., requires_grad=False)
y = w * x + b
y.backward()
print('dy/dx:', x.grad)
print('dy/dw:', w.grad)
print('dy/db:', b.grad)

ValueError: expected sequence of length 2 at dim 1 (got 3)

Since all the required grad is set to false it results in error

In order to calculate derivative, call backward() function on the tensor. The derivatives of tensor w.r.t the input tensors are stored in the .grad property of the respective tensors.

## Function 2 - torch.where(condition, x, y)

Return a tensor of elements selected from either x or y, depending on condition. If the condition is True, the output yields x otherwise y.

In [5]:
# Example 1 - working
x = torch.randn(2, 2)
print(x) 
y = torch.ones(2, 2)
print(y) 
torch.where(x > 0, x, y) 

tensor([[ 0.4130,  0.6360],
        [-0.7099,  0.5681]])
tensor([[1., 1.],
        [1., 1.]])


tensor([[0.4130, 0.6360],
        [1.0000, 0.5681]])

x is a tensor containing random numbers. y is a tensor of ones. We implement the condition x>0, hence the positive elements of tensor x are present in the output tensor, otherwise the elements of y are shown.

In [6]:
# Example 2 - working
x = torch.randn(3, 3)
print(x) 
y = torch.ones(3, 3)
print(y) 
torch.where(x < 0, x, y) 

tensor([[-0.1209, -0.2599,  1.3684],
        [ 0.6254, -1.9796, -0.6828],
        [ 0.3067,  2.9757, -0.1991]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


tensor([[-0.1209, -0.2599,  1.0000],
        [ 1.0000, -1.9796, -0.6828],
        [ 1.0000,  1.0000, -0.1991]])

x is a tensor containing random numbers of dimension 3x3. y is a tensor of ones of dimension 3x3. We implement the condition x<0, hence the negative elements of tensor x are present in the output tensor, otherwise the elements of y are shown.

In [7]:
# Example 3 - breaking 
x = torch.randn(2, 2)
print(x) 
y = torch.ones(3, 3)
print(y) 
torch.where(x > 0, x, y) 

tensor([[-0.7301, -0.0688],
        [-2.7120, -0.2160]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 1

The size of tensor x must match the size of tensor y, as its different in the above shown example it results in error

## Function 3 - torch.unique()

Returns the unique element of the input tensor. The input tensor is passed as an argument to the function.

In [8]:
# Example 1 - working
output, inverse_indices, counts = torch.unique(torch.tensor([1,2,4,5,6,2,2,4,5,6]), sorted=True, return_inverse=True, return_counts=True)
print(output) 
print(inverse_indices)
print(counts)

tensor([1, 2, 4, 5, 6])
tensor([0, 1, 2, 3, 4, 1, 1, 2, 3, 4])
tensor([1, 3, 2, 2, 2])


The first argument to the function is the input tensor on which the function is to be applied. If sorted is set to True, the output tensor is sorted in ascending order. If return_inverse is set to True, there will be an additional returned tensor representing the indices for where elements in the original input map to in the output. If return_counts is set to True, the number of occurences of each element is also returned as a tensor.

In [9]:
# Example 2 - working
counts = torch.unique(torch.tensor([1,2,4,5,6,2,2,4,5,6]))
print(counts)

tensor([1, 2, 4, 5, 6])


Returns only the unique elements of the tensor

In [10]:
# Example 3 - breaking (to illustrate when it breaks)
counts = torch.unique(([1,2,4,5,6,2,2,4,5,6]))
print(counts)

TypeError: _unique2(): argument 'input' (position 1) must be Tensor, not list

The input argument must be a tensor.

## Function 4 - tensor.repeat()

Repeats the tensor along the specified dimensions.

In [11]:
# Example 1 - working
x = torch.tensor([1, 2, 3,4])
y = x.repeat(2, 3)
print(x) 
print(y) 

tensor([1, 2, 3, 4])
tensor([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
        [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]])


Here, the tensor x is repeated along the mentioned dimensions.

In [12]:
# Example 2 - working
x = torch.tensor([7,9,13])
y = x.repeat(3, 3)
print(x) 
print(y) 

tensor([ 7,  9, 13])
tensor([[ 7,  9, 13,  7,  9, 13,  7,  9, 13],
        [ 7,  9, 13,  7,  9, 13,  7,  9, 13],
        [ 7,  9, 13,  7,  9, 13,  7,  9, 13]])


Here, the tensor x is repeated along the dimensions 3x3

In [13]:
# Example 3 - breaking (to illustrate when it breaks)
x = torch.tensor([7,9,0])
y = x.repeat(-1, 0)
print(x) 
print(y)

RuntimeError: Trying to create tensor with negative dimension -1: [-1, 0]

Here, the negative dimension is given which results in the error

This function can be used when repeated tensors are required.

## Function 5 - tensor.fill_diagonal_(fill_value)

Fill the diagonal of the corresponding tensor with the specified value.

In [14]:
# Example 1 - working
t1 = torch.ones(4, 4)
print(t1.fill_diagonal_(0))

tensor([[0., 1., 1., 1.],
        [1., 0., 1., 1.],
        [1., 1., 0., 1.],
        [1., 1., 1., 0.]])


The tensor t1 is filled with 0 at its diagonal.

In [15]:
# Example 2 - working
t2 = torch.ones(5, 3)
print(t2.fill_diagonal_(0, wrap=True))

tensor([[0., 1., 1.],
        [1., 0., 1.],
        [1., 1., 0.],
        [1., 1., 1.],
        [0., 1., 1.]])


The tensor t2 is filled with 0 at its diagonal and since wrap is set to True, the diagonal is wrapped.

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
t2 = torch.tensor([1, 2, 3,4])
print(t2.fill_diagonal_(0.5))

RuntimeError: dimensions must larger than 1

To fill diagonal elements, always the dimension of the tensor must be greater than 1

## Conclusion

These include some interesting fnctions of Pytorch. Their working, usage is explained with the examples. When the fuction breaks is also shown with the help of examples.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for `torch.Tensor`: https://pytorch.org/docs/stable/tensors.html
* https://mc.ai/an-introduction-to-pytorch-functions/
* https://www.analyticsvidhya.com/blog/2018/02/pytorch-tutorial/

In [17]:
!pip install jovian --upgrade --quiet

In [18]:
import jovian

In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
